/*flexberryautogenerated="false"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ICSSoft.STORMNET.Business;
using ICSSoft.STORMNET.Business.LINQProvider;
using System.Collections.Generic;

namespace IIS.Интернет_магазин
{
    public partial class Запрос2 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            Wolv.DataObjectTypes = new[] { typeof(Товар) };
            Wolv.View = Товар.Views.ТоварL;
            Wolv.Operations.New = false;
            Wolv.Operations.Edit = false;
            Wolv.Operations.EditInRow = false;
            Wolv.Operations.Delete = false;
            Wolv.Operations.DeleteInRow = false;
            var ds = (SQLDataService)DataServiceProvider.DataService;
            var goods = ds.Query<Товар>(Товар.Views.ТоварL);




            Wolv.LimitFunction = LinqToLcs.GetLcs(goods.Expression, Товар.Views.ТоварL).LimitFunction;

        }
    }
}
