<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Zapros1.aspx.cs" Inherits="IIS.Интернет_магазин.Запрос1" Title="Untitled Page" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">
    Запрос 1
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <h2 class="<%= Constants.FormHeaderCssClass %> <%= Constants.ListFormHeaderCssClass %>">Запрос</h2>
    <div>
        <h3>Введите диапозон цен</h3>
        от: <ac:AlphaNumericTextBox runat="server" Type="Numeric" ID="Num1"/>
        до: <ac:AlphaNumericTextBox runat="server" Type="Numeric" ID="Num2"/>
        <asp:Button runat="server" Text="Выполнить" ID="Button" OnClick="Button_Click"/>
    </div>
    <div>
        <ac:WebObjectListView runat="server" ID="Wolv"/>
    </div>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
</asp:Content>
