/*flexberryautogenerated="true"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ICSSoft.STORMNET.Business;
//using ICSSoft.STORMNET.Business.LINQProvider;

namespace IIS.Интернет_магазин
{
    public partial class Запрос1 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            Wolv.DataObjectTypes = new[] { typeof(Товар) };
            Wolv.View = Товар.Views.ТоварL;
            Wolv.Operations.New = false;
            Wolv.Operations.Edit = false;
            Wolv.Operations.EditInRow = false;
            Wolv.Operations.Delete = false;
            Wolv.Operations.DeleteInRow = false;
            var ds = DataServiceProvider.DataService;
            if (Session["minPrice"] != null)
            {
                var minPrice = Convert.ToInt32(Session["minPrice"]);
                var q = ds.Query<Товар>(Товар.Views.ТоварL.Name).Where(g => g.Стоимость > minPrice);
                Wolv.LimitFunction = LinqToLcs.GetLcs(q.Expression, Товар.Views.ТоварL).LimitFunction;
            }

        }

        protected void Button_Click(object sender, EventArgs e)
        {
            try 
            {
                int minPrice = Convert.ToInt32(Num1.StringValue);
                int maxPrice = Convert.ToInt32(Num2.StringValue);
                Session["minPrice"] = minPrice;
                Session["maxPrice"] = maxPrice;
            }
            catch
            {
                Session["minPrice"] = null;
                Session["maxPrice"] = null;
            }
            Response.Redirect(Request.Url.ToString());
        }
    }
}
