<%--flexberryautogenerated="false"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Zapros2.aspx.cs" Inherits="IIS.Интернет_магазин.Запрос2" Title="Untitled Page" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">
    Запрос 2
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2 class="<%= Constants.FormHeaderCssClass %> <%= Constants.ListFormHeaderCssClass %>">Товары, не проданные в прошлом месяце</h2>
    <div>
        <asp:Table ID="Table" runat="server" BorderStyle="Solid" BorderWidth="1">
        </asp:Table>
    </div>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
</asp:Content>
