<%--flexberryautogenerated="true"--%>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Zapros4.aspx.cs" Inherits="IIS.Интернет_магазин.Запрос4" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">
    Запрос 4
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2 class="<%= Constants.FormHeaderCssClass %> <%= Constants.ListFormHeaderCssClass %>">Топ-10 товаров, пользующихся спросом (по количеству)</h2>
    <div>
        <asp:Table ID="Table" runat="server" BorderStyle="Solid" BorderWidth="1">
        </asp:Table>
    </div>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
</asp:Content>
