//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Интернет_магазин
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Изменение стоимости.
    /// </summary>
    // *** Start programmer edit section *** (ИзменениеСтоимости CustomAttributes)

    // *** End programmer edit section *** (ИзменениеСтоимости CustomAttributes)
    [AutoAltered()]
    [Caption("Изменение стоимости")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИзменениеСтоимостиE", new string[] {
            "Дата as \'Дата\'",
            "СтараяЦена as \'Старая цена\'",
            "НоваяЦена as \'Новая цена\'",
            "Товар as \'Товар\'",
            "Товар.Наименование as \'Наименование\'"})]
    [View("ИзменениеСтоимостиL", new string[] {
            "Дата as \'Дата\'",
            "СтараяЦена as \'Старая цена\'",
            "НоваяЦена as \'Новая цена\'",
            "Товар.Наименование as \'Наименование\'"})]
    public class ИзменениеСтоимости : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private double fСтараяЦена;
        
        private double fНоваяЦена;
        
        private IIS.Интернет_магазин.Товар fТовар;
        
        // *** Start programmer edit section *** (ИзменениеСтоимости CustomMembers)

        // *** End programmer edit section *** (ИзменениеСтоимости CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ИзменениеСтоимости.Дата CustomAttributes)

        // *** End programmer edit section *** (ИзменениеСтоимости.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ИзменениеСтоимости.Дата Get start)

                // *** End programmer edit section *** (ИзменениеСтоимости.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ИзменениеСтоимости.Дата Get end)

                // *** End programmer edit section *** (ИзменениеСтоимости.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИзменениеСтоимости.Дата Set start)

                // *** End programmer edit section *** (ИзменениеСтоимости.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ИзменениеСтоимости.Дата Set end)

                // *** End programmer edit section *** (ИзменениеСтоимости.Дата Set end)
            }
        }
        
        /// <summary>
        /// СтараяЦена.
        /// </summary>
        // *** Start programmer edit section *** (ИзменениеСтоимости.СтараяЦена CustomAttributes)

        // *** End programmer edit section *** (ИзменениеСтоимости.СтараяЦена CustomAttributes)
        public virtual double СтараяЦена
        {
            get
            {
                // *** Start programmer edit section *** (ИзменениеСтоимости.СтараяЦена Get start)

                // *** End programmer edit section *** (ИзменениеСтоимости.СтараяЦена Get start)
                double result = this.fСтараяЦена;
                // *** Start programmer edit section *** (ИзменениеСтоимости.СтараяЦена Get end)

                // *** End programmer edit section *** (ИзменениеСтоимости.СтараяЦена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИзменениеСтоимости.СтараяЦена Set start)

                // *** End programmer edit section *** (ИзменениеСтоимости.СтараяЦена Set start)
                this.fСтараяЦена = value;
                // *** Start programmer edit section *** (ИзменениеСтоимости.СтараяЦена Set end)

                // *** End programmer edit section *** (ИзменениеСтоимости.СтараяЦена Set end)
            }
        }
        
        /// <summary>
        /// НоваяЦена.
        /// </summary>
        // *** Start programmer edit section *** (ИзменениеСтоимости.НоваяЦена CustomAttributes)

        // *** End programmer edit section *** (ИзменениеСтоимости.НоваяЦена CustomAttributes)
        public virtual double НоваяЦена
        {
            get
            {
                // *** Start programmer edit section *** (ИзменениеСтоимости.НоваяЦена Get start)

                // *** End programmer edit section *** (ИзменениеСтоимости.НоваяЦена Get start)
                double result = this.fНоваяЦена;
                // *** Start programmer edit section *** (ИзменениеСтоимости.НоваяЦена Get end)

                // *** End programmer edit section *** (ИзменениеСтоимости.НоваяЦена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИзменениеСтоимости.НоваяЦена Set start)

                // *** End programmer edit section *** (ИзменениеСтоимости.НоваяЦена Set start)
                this.fНоваяЦена = value;
                // *** Start programmer edit section *** (ИзменениеСтоимости.НоваяЦена Set end)

                // *** End programmer edit section *** (ИзменениеСтоимости.НоваяЦена Set end)
            }
        }
        
        /// <summary>
        /// Изменение стоимости.
        /// </summary>
        // *** Start programmer edit section *** (ИзменениеСтоимости.Товар CustomAttributes)

        // *** End programmer edit section *** (ИзменениеСтоимости.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.Интернет_магазин.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (ИзменениеСтоимости.Товар Get start)

                // *** End programmer edit section *** (ИзменениеСтоимости.Товар Get start)
                IIS.Интернет_магазин.Товар result = this.fТовар;
                // *** Start programmer edit section *** (ИзменениеСтоимости.Товар Get end)

                // *** End programmer edit section *** (ИзменениеСтоимости.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИзменениеСтоимости.Товар Set start)

                // *** End programmer edit section *** (ИзменениеСтоимости.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (ИзменениеСтоимости.Товар Set end)

                // *** End programmer edit section *** (ИзменениеСтоимости.Товар Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИзменениеСтоимостиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИзменениеСтоимостиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИзменениеСтоимостиE", typeof(IIS.Интернет_магазин.ИзменениеСтоимости));
                }
            }
            
            /// <summary>
            /// "ИзменениеСтоимостиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИзменениеСтоимостиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИзменениеСтоимостиL", typeof(IIS.Интернет_магазин.ИзменениеСтоимости));
                }
            }
        }
    }
}
