//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Интернет_магазин
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Бизнес сервер.
    /// </summary>
    // *** Start programmer edit section *** (BFБизнесСервер CustomAttributes)

    // *** End programmer edit section *** (BFБизнесСервер CustomAttributes)
    public class BFБизнесСервер : ICSSoft.STORMNET.Business.BFBase
    {
        
        // *** Start programmer edit section *** (BFБизнесСервер CustomMembers)

        // *** End programmer edit section *** (BFБизнесСервер CustomMembers)

    }
}
