/*flexberryautogenerated="true"*/
namespace IIS.Интернет_магазин
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class ИзменениеСтоимостиL : BaseListForm<ИзменениеСтоимости>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ИзменениеСтоимостиL() : base(ИзменениеСтоимости.Views.ИзменениеСтоимостиL)
        {
            EditPage = ИзменениеСтоимостиE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Products/IzmenenieStoimostiL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
